---
title: "p8105 homework 5"
author: "Xintao Ding"
date: "11/9/2019"
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

```


## Problem 1 
write a function that takes a vector as an argument; replaces missing values using the rules defined above; and returns the resulting vector;apply this function to the columns of iris_with_missing using a map statement
```{r}
set.seed(10)
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

#define a function
missing_values_replacement = function(x) {
  if(is.numeric(x)) {
    replace(x, is.na(x), mean(x, na.rm = TRUE)) #replace numeric missing values with mean 
  } else if (is.character(x)) {
    replace(x, is.na(x), "virginica")   #replace character missing values with a certain word
}
  }

iris_withnot_missing = map_dfr(iris_with_missing, missing_values_replacement) # map the function to iris_with_missing
iris_withnot_missing
```

## Problem 2

```{r message = FALSE, warning = FALSE}
# create a dataframe with list file names
file_name <- list.files("./data") 
df <- tibble(file_name)
df <- df %>% 
  mutate(outcome = map(file_name, ~read_csv(str_c("./data/", .x)))) # iterate file names and save as a new variable
df

# tidy data frame
tidy_df <- df %>% 
  separate(file_name, into = c("arm", "subject_id"), sep = "_") %>% 
  mutate (subject_id = gsub("\\.csv", "", subject_id)) %>%  # include subject ID
  unnest() %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "outcome"
  )
  
tidy_df

# plotting
plot <- tidy_df %>% 
  ggplot(aes(x = week, y = outcome, group = subject_id, color = subject_id)) +
  geom_line()+
  facet_grid(~arm)+
  labs(title = "Observatinos on Each Subject over Time")
plot
```


##Problem 3
```{r}

```

